const data = [
  {
    id: 1,
    category: "uiux",
    image: "/assets/projects/project1.jpg",
    title: "Project Title One (UIUX)",
    desc: "Provident similique accusantium nemo autem.",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 2,
    category: "frontend",
    image: "/assets/projects/project2.jpg",
    title: "Project Title Two (Frontend)",
    desc: "Provident similique accusantium nemo autem.",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 3,
    category: "frontend",
    image: "/assets/projects/project3.jpg",
    title: "Project Title Three (Frontend)",
    desc: "Provident similique accusantium nemo autem.",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 4,
    category: "uiux",
    image: "/assets/projects/project4.jpg",
    title: "Project Title Four (UIUX)",
    desc: "Provident similique accusantium nemo autem.",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 5,
    category: "uiux",
    image: "/assets/projects/project5.jpg",
    title: "Project Title Five (UIUX)",
    desc: "Provident similique accusantium nemo autem.",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 6,
    category: "frontend",
    image: "/assets/projects/project6.jpg",
    title: "Project Title Six (Frontend)",
    desc: "Provident similique accusantium nemo autem.",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 7,
    category: "frontend",
    image: "/assets/projects/project7.jpg",
    title: "Project Title Seven (Frontend)",
    desc: "Provident similique accusantium nemo autem.",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 8,
    category: "backend",
    image: "/assets/projects/project8.jpg",
    title: "Project Title Eight (Backend)",
    desc: "Provident similique accusantium nemo autem.",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
  {
    id: 9,
    category: "frontend",
    image: "/assets/projects/project9.jpg",
    title: "Project Title Nine (Frontend)",
    desc: "Provident similique accusantium nemo autem.",
    demo: "http://egatortutorials.com",
    github: "https://github.com/egattor",
  },
];

export default data;
